/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/session/country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminSetCountry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListOperations"];
        put?: never;
        post: operations["adminSubmitOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations/{change_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminApproveOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations/{change_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRejectOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListOperationAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AdminRole: "SUPER_ADMIN" | "COUNTRY_ADMIN" | "CONTENT_ADMIN" | "SUPPORT_ADMIN" | "AUDITOR";
        AdminAssurance: {
            mfa_satisfied: boolean;
            fresh_auth: boolean;
            /** Format: date-time */
            auth_time: string;
        };
        NavigationItem: {
            id: string;
            label: string;
            path: string;
            capability: string;
        };
        AdminSession: {
            subject_id: string;
            display_name: string;
            roles: components["schemas"]["AdminRole"][];
            capabilities: string[];
            allowed_countries: string[];
            selected_country: string;
            assurance: components["schemas"]["AdminAssurance"];
            navigation: components["schemas"]["NavigationItem"][];
            csrf_token: string;
        };
        CountrySelection: {
            country: string;
        };
        /** @enum {string} */
        AdminOperationDomain: "CATALOG" | "ORDER" | "PAYMENT" | "WALLET" | "CAMPAIGN" | "SUPPORT" | "REPORTING";
        /** @enum {string} */
        AdminOperationRisk: "STANDARD" | "HIGH";
        /** @enum {string} */
        AdminOperationStatus: "PENDING_APPROVAL" | "EXECUTED" | "REJECTED";
        AdminOperationInput: {
            domain: components["schemas"]["AdminOperationDomain"];
            action: string;
            target_id: string;
            reason: string;
            payload: {
                [key: string]: unknown;
            };
        };
        AdminOperationCommand: components["schemas"]["AdminOperationInput"] & {
            correlation_id: string;
        };
        AdminOperationChange: {
            id: string;
            /** Format: int64 */
            revision: number;
            tenant_id: string;
            country: string;
            command: components["schemas"]["AdminOperationCommand"];
            risk: components["schemas"]["AdminOperationRisk"];
            status: components["schemas"]["AdminOperationStatus"];
            requested_by: string;
            approved_by?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminOperationPage: {
            changes: components["schemas"]["AdminOperationChange"][];
        };
        AdminOperationDecision: {
            /** Format: int64 */
            expected_revision: number;
        };
        AdminOperationRejection: {
            /** Format: int64 */
            expected_revision: number;
            reason: string;
        };
        AdminOperationAuditEvent: {
            /** Format: int64 */
            sequence: number;
            tenant_id: string;
            country: string;
            actor_id: string;
            action: string;
            target_id: string;
            /** @enum {string} */
            outcome: "SUCCEEDED" | "DENIED" | "FAILED";
            reason: string;
            correlation_id: string;
            /** Format: date-time */
            created_at: string;
        };
        AdminOperationAuditPage: {
            events: components["schemas"]["AdminOperationAuditEvent"][];
        };
        /** @enum {string} */
        AuditOutcome: "SUCCEEDED" | "DENIED" | "FAILED";
        AuditActor: {
            subject_id: string;
            /** @enum {string} */
            actor_type: "USER" | "SERVICE" | "SYSTEM";
            ip_prefix?: string;
        };
        AuditTarget: {
            type: string;
            id: string;
        };
        AuditEntry: {
            id: string;
            tenant_id: string;
            country: string;
            actor: components["schemas"]["AuditActor"];
            action: string;
            target: components["schemas"]["AuditTarget"];
            outcome: components["schemas"]["AuditOutcome"];
            reason_code: string;
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            recorded_at: string;
            hash: string;
            /** Format: int64 */
            sequence: number;
        };
        AuditPage: {
            entries: components["schemas"]["AuditEntry"][];
            next_cursor?: string;
            has_more: boolean;
        };
        CorrelationID: string;
        FieldError: {
            field: string;
            code: string;
            message: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            correlation_id: components["schemas"]["CorrelationID"];
            retryable: boolean;
            field_errors: components["schemas"]["FieldError"][];
            details: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
    };
    responses: {
        /** @description Safe standard error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminGetSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authorized administrator context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminSetCountry: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CountrySelection"];
            };
        };
        responses: {
            /** @description Country context changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListAuditEvents: {
        parameters: {
            query?: {
                actor_id?: string;
                action?: string;
                target_id?: string;
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events restricted to the session tenant and selected country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changes visible to the administrator in the selected country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminSubmitOperation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOperationInput"];
            };
        };
        responses: {
            /** @description Executed standard-risk change or high-risk change awaiting four-eyes approval */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationChange"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminApproveOperation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOperationDecision"];
            };
        };
        responses: {
            /** @description Change approved and executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationChange"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminRejectOperation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOperationRejection"];
            };
        };
        responses: {
            /** @description Change rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationChange"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListOperationAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable privileged-operation audit evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationAuditPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
}
