/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/session/country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminSetCountry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AdminRole: "SUPER_ADMIN" | "COUNTRY_ADMIN" | "CONTENT_ADMIN" | "SUPPORT_ADMIN" | "AUDITOR";
        AdminAssurance: {
            mfa_satisfied: boolean;
            fresh_auth: boolean;
            /** Format: date-time */
            auth_time: string;
        };
        NavigationItem: {
            id: string;
            label: string;
            path: string;
            capability: string;
        };
        AdminSession: {
            subject_id: string;
            display_name: string;
            roles: components["schemas"]["AdminRole"][];
            capabilities: string[];
            allowed_countries: string[];
            selected_country: string;
            assurance: components["schemas"]["AdminAssurance"];
            navigation: components["schemas"]["NavigationItem"][];
            csrf_token: string;
        };
        CountrySelection: {
            country: string;
        };
        /** @enum {string} */
        AuditOutcome: "SUCCEEDED" | "DENIED" | "FAILED";
        AuditActor: {
            subject_id: string;
            /** @enum {string} */
            actor_type: "USER" | "SERVICE" | "SYSTEM";
            ip_prefix?: string;
        };
        AuditTarget: {
            type: string;
            id: string;
        };
        AuditEntry: {
            id: string;
            tenant_id: string;
            country: string;
            actor: components["schemas"]["AuditActor"];
            action: string;
            target: components["schemas"]["AuditTarget"];
            outcome: components["schemas"]["AuditOutcome"];
            reason_code: string;
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            recorded_at: string;
            hash: string;
            /** Format: int64 */
            sequence: number;
        };
        AuditPage: {
            entries: components["schemas"]["AuditEntry"][];
            next_cursor?: string;
            has_more: boolean;
        };
        CorrelationID: string;
        FieldError: {
            field: string;
            code: string;
            message: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            correlation_id: components["schemas"]["CorrelationID"];
            retryable: boolean;
            field_errors: components["schemas"]["FieldError"][];
            details: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
    };
    responses: {
        /** @description Safe standard error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminGetSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authorized administrator context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminSetCountry: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CountrySelection"];
            };
        };
        responses: {
            /** @description Country context changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListAuditEvents: {
        parameters: {
            query?: {
                actor_id?: string;
                action?: string;
                target_id?: string;
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events restricted to the session tenant and selected country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
}
