/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/admin-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminExchangeVerifiedSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetSession"];
        put?: never;
        post?: never;
        delete: operations["adminEndSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/session/country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminSetCountry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListOperations"];
        put?: never;
        post: operations["adminSubmitOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations/{change_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminApproveOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations/{change_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRejectOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/cms/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListCMSPageDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/cms/pages/{page_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminSaveCMSPageDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/cms/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetCMSWorkspaceDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/cms/workspace/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminSaveCMSWorkspaceDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/governance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetGovernance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetReportDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/reports/{report_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminCreateReportExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/report-exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetReportExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/report-exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminDownloadReportExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListSupportTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/operations/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListOperationAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AdminRole: "SUPER_ADMIN" | "COUNTRY_ADMIN" | "CONTENT_ADMIN" | "SUPPORT_ADMIN" | "AUDITOR";
        AdminSessionAssertion: {
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            tenant_id: string;
            display_name: string;
            roles: components["schemas"]["AdminRole"][];
            allowed_countries: string[];
            selected_country: string;
            /** Format: date-time */
            authenticated_at: string;
            auth_methods: string[];
        };
        AdminSessionExchangeResult: {
            /** Format: date-time */
            expires_at: string;
        };
        AdminAssurance: {
            mfa_satisfied: boolean;
            fresh_auth: boolean;
            /** Format: date-time */
            auth_time: string;
        };
        NavigationItem: {
            id: string;
            label: string;
            path: string;
            capability: string;
        };
        AdminSession: {
            subject_id: string;
            display_name: string;
            roles: components["schemas"]["AdminRole"][];
            capabilities: string[];
            allowed_countries: string[];
            selected_country: string;
            assurance: components["schemas"]["AdminAssurance"];
            navigation: components["schemas"]["NavigationItem"][];
            csrf_token: string;
        };
        CountrySelection: {
            country: string;
        };
        /** @enum {string} */
        AdminOperationDomain: "CATALOG" | "ORDER" | "PAYMENT" | "WALLET" | "CAMPAIGN" | "CMS" | "SUPPORT" | "REPORTING" | "SUPPLY" | "RESTAURANT" | "DISPATCH" | "SETTLEMENT" | "FRANCHISE" | "CONTENT" | "POLICY" | "COUNTRY" | "EMERGENCY" | "INTELLIGENCE";
        /** @enum {string} */
        Role: "CUSTOMER" | "VENDOR" | "RIDER";
        /** @enum {string} */
        TicketStatus: "OPEN" | "WAITING_FOR_SUPPORT" | "WAITING_FOR_REQUESTER" | "RESOLVED" | "CLOSED";
        /** @enum {string} */
        TicketCategory: "ACCOUNT" | "ORDER" | "PAYMENT" | "VENDOR_OPERATIONS" | "RIDER_OPERATIONS" | "OTHER";
        /** @enum {string} */
        TicketPriority: "LOW" | "NORMAL" | "HIGH" | "URGENT";
        AdminTicket: {
            /** Format: uuid */
            id: string;
            owner_role: components["schemas"]["Role"];
            /** @description Opaque identity reference; no contact PII is exposed. */
            owner_reference: string;
            category: components["schemas"]["TicketCategory"];
            subject: string;
            related_reference?: string;
            priority: components["schemas"]["TicketPriority"];
            status: components["schemas"]["TicketStatus"];
            message_count: number;
            /** Format: date-time */
            last_message_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminTicketPage: {
            items: components["schemas"]["AdminTicket"][];
            next_cursor?: string;
        };
        GovernanceMetric: {
            id: string;
            title: string;
            /** Format: int64 */
            value: number;
            unit: string;
            /** Format: date-time */
            freshness: string;
            masked: boolean;
        };
        GovernanceView: {
            country: string;
            policy_version: string;
            feature_flags: {
                [key: string]: boolean;
            };
            metrics: components["schemas"]["GovernanceMetric"][];
            /** @enum {string} */
            privacy_mode: "aggregate_and_masked";
            /** Format: date-time */
            generated_at: string;
        };
        ReportSummary: {
            id: string;
            title: string;
            domain: string;
            metric: string;
            /** Format: int64 */
            value: number;
            unit: string;
            /** Format: date-time */
            freshness: string;
            masked: boolean;
            /** @enum {string} */
            export_policy: "MFA_AND_AUDIT_REQUIRED";
        };
        ReportPage: {
            items: components["schemas"]["ReportSummary"][];
            next_cursor?: string;
        };
        ReportRow: {
            label: string;
            dimensions: {
                [key: string]: string;
            };
            /** Format: int64 */
            value: number;
            unit: string;
        };
        ReportLineage: {
            source_projection: string;
            aggregation: string;
            /** Format: date-time */
            freshness: string;
            /** Format: date-time */
            generated_at: string;
        };
        ReportDetail: {
            report: components["schemas"]["ReportSummary"];
            country: string;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            items: components["schemas"]["ReportRow"][];
            next_cursor?: string;
            lineage: components["schemas"]["ReportLineage"];
        };
        CreateReportExportRequest: {
            /** @enum {string} */
            format: "CSV";
            reason: string;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        ReportExport: {
            id: string;
            report_id: string;
            /** @enum {string} */
            format: "CSV";
            /** @enum {string} */
            status: "PROCESSING" | "READY" | "FAILED";
            /** @enum {string} */
            content_type?: "text/csv; charset=utf-8";
            file_name?: string;
            checksum_sha256?: string;
            /** Format: int64 */
            size_bytes?: number;
            download_url?: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        AdminOperationRisk: "STANDARD" | "HIGH";
        /** @enum {string} */
        AdminOperationStatus: "PENDING_APPROVAL" | "EXECUTED" | "REJECTED";
        CMSPageDraftInput: {
            /** Format: int64 */
            expected_revision: number;
            page: components["schemas"]["Page"];
        };
        CMSPageDraft: {
            tenant_id: string;
            country: string;
            page: components["schemas"]["Page"];
            /** Format: int64 */
            revision: number;
            updated_by: string;
            /** Format: date-time */
            updated_at: string;
        };
        CMSPageDraftPage: {
            items: components["schemas"]["CMSPageDraft"][];
        };
        CMSWorkspaceDraftInput: {
            /** Format: int64 */
            expected_revision: number;
            workspace: components["schemas"]["Workspace"];
        };
        CMSWorkspaceDraft: {
            /** Format: uuid */
            tenant_id: string;
            country: string;
            workspace: components["schemas"]["Workspace"];
            /** Format: int64 */
            revision: number;
            updated_by: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminOperationInput: {
            domain: components["schemas"]["AdminOperationDomain"];
            action: string;
            target_id: string;
            reason: string;
            payload: {
                [key: string]: unknown;
            };
        };
        AdminOperationCommand: components["schemas"]["AdminOperationInput"] & {
            correlation_id: string;
        };
        AdminOperationChange: {
            id: string;
            /** Format: int64 */
            revision: number;
            tenant_id: string;
            country: string;
            command: components["schemas"]["AdminOperationCommand"];
            risk: components["schemas"]["AdminOperationRisk"];
            status: components["schemas"]["AdminOperationStatus"];
            requested_by: string;
            approved_by?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminOperationPage: {
            changes: components["schemas"]["AdminOperationChange"][];
        };
        AdminOperationDecision: {
            /** Format: int64 */
            expected_revision: number;
        };
        AdminOperationRejection: {
            /** Format: int64 */
            expected_revision: number;
            reason: string;
        };
        AdminOperationAuditEvent: {
            /** Format: int64 */
            sequence: number;
            tenant_id: string;
            country: string;
            actor_id: string;
            action: string;
            target_id: string;
            /** @enum {string} */
            outcome: "SUCCEEDED" | "DENIED" | "FAILED";
            reason: string;
            correlation_id: string;
            /** Format: date-time */
            created_at: string;
        };
        AdminOperationAuditPage: {
            events: components["schemas"]["AdminOperationAuditEvent"][];
        };
        /** @enum {string} */
        AuditOutcome: "SUCCEEDED" | "DENIED" | "FAILED";
        AuditActor: {
            subject_id: string;
            /** @enum {string} */
            actor_type: "USER" | "SERVICE" | "SYSTEM";
            ip_prefix?: string;
        };
        AuditTarget: {
            type: string;
            id: string;
        };
        AuditEntry: {
            id: string;
            tenant_id: string;
            country: string;
            actor: components["schemas"]["AuditActor"];
            action: string;
            target: components["schemas"]["AuditTarget"];
            outcome: components["schemas"]["AuditOutcome"];
            reason_code: string;
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            recorded_at: string;
            hash: string;
            /** Format: int64 */
            sequence: number;
        };
        AuditPage: {
            entries: components["schemas"]["AuditEntry"][];
            next_cursor?: string;
            has_more: boolean;
        };
        CorrelationID: string;
        FieldError: {
            field: string;
            code: string;
            message: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            correlation_id: components["schemas"]["CorrelationID"];
            retryable: boolean;
            field_errors: components["schemas"]["FieldError"][];
            details: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        PageBlock: {
            id: string;
            kind: string;
            title_key?: string;
            enabled: boolean;
            priority: number;
            content: {
                [key: string]: unknown;
            };
        };
        Page: {
            id: string;
            route: string;
            title_key: string;
            audience: ("PUBLIC" | "CUSTOMER" | "VENDOR" | "RIDER")[];
            enabled: boolean;
            blocks: components["schemas"]["PageBlock"][];
        };
        /** @enum {string} */
        Locale: "en" | "ta" | "hi" | "te" | "kn" | "ml" | "mr" | "bn" | "gu";
        ConsentPolicy: {
            purpose: string;
            policy_version: string;
            required: boolean;
        };
        HomeSection: {
            id: string;
            kind: string;
            title_key: string;
            enabled: boolean;
            priority: number;
        };
        MaintenanceWindow: {
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            message: string;
        };
        Workspace: {
            minimum_versions: {
                ANDROID: string;
                IOS: string;
                WEB: string;
            };
            latest_versions: {
                ANDROID: string;
                IOS: string;
                WEB: string;
            };
            supported_locales: components["schemas"]["Locale"][];
            default_locale: components["schemas"]["Locale"];
            consent_policies: components["schemas"]["ConsentPolicy"][];
            flags: {
                [key: string]: boolean;
            };
            home_sections: components["schemas"]["HomeSection"][];
            maintenance_window?: components["schemas"]["MaintenanceWindow"];
        };
    };
    responses: {
        /** @description Safe standard error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CSRFToken: string;
        ReportID: string;
        ExportID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminExchangeVerifiedSession: {
        parameters: {
            query?: never;
            header: {
                "X-P4U-Admin-Timestamp": string;
                "X-P4U-Admin-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSessionAssertion"];
            };
        };
        responses: {
            /** @description Opaque browser session issued from a verified upstream identity assertion */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionExchangeResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminGetSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authorized administrator context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminEndSession: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator session revoked and cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    adminSetCountry: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CountrySelection"];
            };
        };
        responses: {
            /** @description Country context changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListAuditEvents: {
        parameters: {
            query?: {
                actor_id?: string;
                action?: string;
                target_id?: string;
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events restricted to the session tenant and selected country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changes visible to the administrator in the selected country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminSubmitOperation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOperationInput"];
            };
        };
        responses: {
            /** @description Executed standard-risk change or high-risk change awaiting four-eyes approval */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationChange"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminApproveOperation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOperationDecision"];
            };
        };
        responses: {
            /** @description Change approved and executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationChange"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminRejectOperation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOperationRejection"];
            };
        };
        responses: {
            /** @description Change rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationChange"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminListCMSPageDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-scoped CMS page drafts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CMSPageDraftPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminSaveCMSPageDraft: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CMSPageDraftInput"];
            };
        };
        responses: {
            /** @description Revision-safe CMS page draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CMSPageDraft"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminGetCMSWorkspaceDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-scoped global mobile configuration draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CMSWorkspaceDraft"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    adminSaveCMSWorkspaceDraft: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CMSWorkspaceDraftInput"];
            };
        };
        responses: {
            /** @description Revision-safe global mobile configuration draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CMSWorkspaceDraft"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminGetGovernance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-scoped aggregate governance dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceView"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminListReports: {
        parameters: {
            query?: {
                domain?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-scoped published report catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminGetReportDetail: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                report_id: components["parameters"]["ReportID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered aggregate report detail with data lineage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminCreateReportExport: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                report_id: components["parameters"]["ReportID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportExportRequest"];
            };
        };
        responses: {
            /** @description Audited export materialization accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportExport"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminGetReportExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: components["parameters"]["ExportID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-scoped export status and signed artifact metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportExport"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    adminDownloadReportExport: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                export_id: components["parameters"]["ExportID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed, short-lived CSV report artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    adminListSupportTickets: {
        parameters: {
            query?: {
                owner_role?: components["schemas"]["Role"];
                status?: components["schemas"]["TicketStatus"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-scoped support administration queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTicketPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    adminListOperationAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable privileged-operation audit evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOperationAuditPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
}
