package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type fixture struct {
	goName   string
	dartName string
	path     string
}

var fixtures = []fixture{
	{goName: "AuditEntryFixtureJSON", dartName: "auditEntryFixtureJson", path: "api/fixtures/audit_entry.json"},
	{goName: "BootstrapFixtureJSON", dartName: "bootstrapFixtureJson", path: "api/fixtures/bootstrap.json"},
	{goName: "CatalogHomeFixtureJSON", dartName: "catalogHomeFixtureJson", path: "api/fixtures/catalog_home.json"},
	{goName: "DomainEventFixtureJSON", dartName: "domainEventFixtureJson", path: "api/fixtures/domain_event.json"},
	{goName: "IdentityAuthenticationFixtureJSON", dartName: "identityAuthenticationFixtureJson", path: "api/fixtures/identity_authentication.json"},
	{goName: "MediaAssetFixtureJSON", dartName: "mediaAssetFixtureJson", path: "api/fixtures/media_asset.json"},
	{goName: "ProblemFixtureJSON", dartName: "problemFixtureJson", path: "api/fixtures/problem.json"},
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail when generated outputs are stale")
	flag.Parse()

	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	for _, contractPath := range []string{
		"api/openapi/audit.openapi.json",
		"api/openapi/common.openapi.json",
		"api/openapi/catalog.openapi.json",
		"api/openapi/configuration.openapi.json",
		"api/openapi/identity.openapi.json",
		"api/openapi/media.openapi.json",
		"api/asyncapi/common.asyncapi.json",
	} {
		contents, err := os.ReadFile(filepath.Join(root, contractPath))
		if err != nil {
			return fmt.Errorf("read %s: %w", contractPath, err)
		}
		var document map[string]any
		if err := json.Unmarshal(contents, &document); err != nil {
			return fmt.Errorf("parse %s: %w", contractPath, err)
		}
	}

	sort.Slice(fixtures, func(left, right int) bool {
		return fixtures[left].path < fixtures[right].path
	})

	goOutput, dartOutput, err := renderFixtures(root)
	if err != nil {
		return err
	}

	outputs := map[string][]byte{
		"internal/contracts/generated/fixtures.gen.go":       goOutput,
		"generated/dart/lib/common_contract_fixtures.g.dart": dartOutput,
	}
	for outputPath, expected := range outputs {
		absolutePath := filepath.Join(root, outputPath)
		if check {
			actual, err := os.ReadFile(absolutePath)
			if err != nil {
				return fmt.Errorf("read generated output %s: %w", outputPath, err)
			}
			if !bytes.Equal(actual, expected) {
				return fmt.Errorf("generated output %s is stale; run make contract-generate", outputPath)
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(absolutePath), 0o755); err != nil {
			return fmt.Errorf("create output directory for %s: %w", outputPath, err)
		}
		if err := os.WriteFile(absolutePath, expected, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outputPath, err)
		}
	}

	return nil
}

func renderFixtures(root string) ([]byte, []byte, error) {
	var goSource strings.Builder
	goSource.WriteString("// Code generated by cmd/contractgen; DO NOT EDIT.\n\n")
	goSource.WriteString("package generated\n\nconst (\n")

	var dartSource strings.Builder
	dartSource.WriteString("// Code generated by cmd/contractgen; DO NOT EDIT.\n")
	dartSource.WriteString("// ignore_for_file: lines_longer_than_80_chars\n\n")

	for _, item := range fixtures {
		contents, err := os.ReadFile(filepath.Join(root, item.path))
		if err != nil {
			return nil, nil, fmt.Errorf("read fixture %s: %w", item.path, err)
		}
		var value any
		if err := json.Unmarshal(contents, &value); err != nil {
			return nil, nil, fmt.Errorf("parse fixture %s: %w", item.path, err)
		}
		canonical, err := json.Marshal(value)
		if err != nil {
			return nil, nil, fmt.Errorf("encode fixture %s: %w", item.path, err)
		}

		goSource.WriteString("\t")
		goSource.WriteString(item.goName)
		goSource.WriteString(" = ")
		goSource.WriteString(strconv.Quote(string(canonical)))
		goSource.WriteString("\n")

		dartSource.WriteString("const String ")
		dartSource.WriteString(item.dartName)
		dartSource.WriteString(" = r'''")
		dartSource.Write(canonical)
		dartSource.WriteString("''';\n")
	}
	goSource.WriteString(")\n")

	formattedGo, err := format.Source([]byte(goSource.String()))
	if err != nil {
		return nil, nil, fmt.Errorf("format generated Go fixtures: %w", err)
	}
	return formattedGo, []byte(dartSource.String()), nil
}
